spring:
  application:
    name: demo-Replica-basic
  datasource:
    master:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password

    replica:
      url: jdbc:postgresql://localhost:5433/postgres
      username: postgres
      password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgresSQLDialect
