spring:
  application:
    name: demo-Replica-basic
  datasource:
    master:
      url: jdbc:postgresql://localhost:5432/postgres
      username: root
      password: root

    replica:
      url: jdbc:postgresql://localhost:5433/postgres
      username: root
      password: root

logging:
  level:
    com.zaxxer.hikari.HikariDataSource: DEBUG